version: '3.8'

services:
  # OTEL Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      - weather-network

  # Zipkin para tracing distribuído
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
    networks:
      - weather-network

  # Serviço A - Validação de CEP
  service-a:
    build:
      context: ./service-a
      dockerfile: Dockerfile
    container_name: service-a
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SERVICE_B_URL=http://service-b:8081
      - ZIPKIN_URL=http://zipkin:9411
      - OTEL_COLLECTOR_URL=http://otel-collector:4317
    depends_on:
      - otel-collector
      - zipkin
      - service-b
    networks:
      - weather-network

  # Serviço B - Orquestração de CEP e Temperatura
  service-b:
    build:
      context: ./service-b
      dockerfile: Dockerfile
    container_name: service-b
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - ZIPKIN_URL=http://zipkin:9411
      - OTEL_COLLECTOR_URL=http://otel-collector:4317
    depends_on:
      - otel-collector
      - zipkin
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge
